repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=100]
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: no-commit-to-branch
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
- repo: https://github.com/homebysix/pre-commit-macadmin
  rev: 6bff9cc739eac92a945ce05d7cabe7a23abcec7e
  hooks:
  - id: check-autopkg-recipes
  - id: forbid-autopkg-overrides
